
import { theme, FONT_MONO, FONT_UI } from './theme.js';

const C = theme;

function getStyles() {
  return {
    root: {
      width: "100vw",
      height: "100vh",
      display: "flex",
      flexDirection: "column",
      fontFamily: FONT_UI,
      fontSize: 13,
      color: C.text,
      background: C.bg,
      overflow: "hidden",
      cursor: "default",
      userSelect: "none",
    },
    menuBar: {
      display: "flex",
      alignItems: "center",
      height: 26,
      background: C.menuBg,
      borderBottom: `1px solid ${C.borderLight}`,
      padding: "0 4px",
      flexShrink: 0,
    },
    menuLeft: { display: "flex", alignItems: "center" },
    menuRight: { flex: 1, textAlign: "right", paddingRight: 8 },
    menuItem: {
      padding: "3px 8px",
      fontSize: 12,
      color: C.text,
      cursor: "pointer",
      borderRadius: 3,
      transition: "background 0.1s",
    },
    toolbar: {
      display: "flex",
      alignItems: "center",
      height: 30,
      background: C.toolbarBg,
      borderBottom: `1px solid ${C.borderLight}`,
      padding: "0 6px",
      gap: 2,
      flexShrink: 0,
    },
    toolbarGroup: { display: "flex", alignItems: "center", gap: 2 },
    toolBtn: {
      background: "none",
      border: "none",
      padding: "3px 5px",
      cursor: "pointer",
      borderRadius: 3,
      display: "flex",
      alignItems: "center",
      color: C.textLight,
    },
    mainArea: {
      flex: 1,
      display: "flex",
      overflow: "hidden",
      minHeight: 0,
    },
    leftCol: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      minWidth: 0,
      borderRight: `1px solid ${C.border}`,
    },
    rightCol: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      minWidth: 0,
    },
    resizeHandle: {
      width: 5,
      background: C.toolbarBg,
      cursor: "col-resize",
      flexShrink: 0,
    },
    splitterV: {
      width: 5,
      cursor: "col-resize",
      background: C.toolbarBg,
      flexShrink: 0,
      zIndex: 2,
    },
    splitterH: {
      height: 5,
      cursor: "row-resize",
      background: C.toolbarBg,
      flexShrink: 0,
      zIndex: 2,
    },
    paneButtons: {
      display: "flex",
      alignItems: "center",
      marginLeft: "auto",
      gap: 2,
      paddingRight: 4,
    },
    paneMinMaxBtn: {
      background: "none",
      border: "none",
      padding: "2px 4px",
      cursor: "pointer",
      color: C.textMuted,
      fontSize: 10,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 2,
    },
    tabCloseBtn: {
      marginLeft: 6,
      width: 16,
      height: 16,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 3,
      fontSize: 13,
      color: C.textMuted,
      cursor: "pointer",
      background: "transparent",
      border: "none",
      lineHeight: 1,
      flexShrink: 0,
    },
    tabAddBtn: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: 28,
      height: 28,
      cursor: "pointer",
      color: C.textMuted,
      fontSize: 18,
      background: C.tabInactive,
      borderRight: `1px solid ${C.borderLight}`,
      flexShrink: 0,
    },
    editorGutter: {
      width: 50,
      overflowY: "hidden",
      overflowX: "hidden",
      background: C.gutterBg,
      flexShrink: 0,
      paddingTop: 2,
      paddingBottom: 2,
    },
    editorDisplay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      overflowY: "hidden",
      overflowX: "hidden",
      pointerEvents: "none",
      fontFamily: FONT_MONO,
      fontSize: 12,
      lineHeight: "18px",
      paddingTop: 2,
      paddingBottom: 2,
    },
    editorDisplayLine: {
      paddingLeft: 8,
      whiteSpace: "pre",
      color: C.text,
      minHeight: 18,
      lineHeight: "18px",
    },
    editorTextarea: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      fontFamily: FONT_MONO,
      fontSize: 12,
      lineHeight: "18px",
      paddingTop: 2,
      paddingBottom: 2,
      paddingLeft: 8,
      paddingRight: 8,
      color: "transparent",
      caretColor: C.text,
      background: "transparent",
      border: "none",
      outline: "none",
      resize: "none",
      whiteSpace: "pre",
      overflowY: "auto",
      overflowX: "auto",
      tabSize: 2,
      zIndex: 1,
    },
    consoleWdBar: {
      height: 20,
      display: "flex",
      alignItems: "center",
      padding: "0 8px",
      fontSize: 11,
      color: C.textMuted,
      background: C.toolbarBg,
      borderTop: `1px solid ${C.borderLight}`,
      flexShrink: 0,
    },
    pane: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      borderBottom: `1px solid ${C.border}`,
      minHeight: 0,
      overflow: "hidden",
    },
    paneTabs: {
      display: "flex",
      alignItems: "stretch",
      height: 28,
      background: C.tabInactive,
      borderBottom: `1px solid ${C.tabBorder}`,
      flexShrink: 0,
      overflow: "hidden",
    },
    paneTab: {
      display: "flex",
      alignItems: "center",
      padding: "0 12px",
      fontSize: 12,
      color: C.textLight,
      cursor: "pointer",
      borderRight: `1px solid ${C.borderLight}`,
      background: C.tabInactive,
      whiteSpace: "nowrap",
    },
    paneTabActive: {
      background: C.tabActive,
      color: C.text,
      borderBottom: "2px solid transparent",
      fontWeight: 500,
    },
    editorToolbar: {
      display: "flex",
      alignItems: "center",
      height: 24,
      background: C.toolbarBg,
      borderBottom: `1px solid ${C.borderLight}`,
      padding: "0 4px",
      gap: 2,
      flexShrink: 0,
    },
    editorBtn: {
      background: "none",
      border: "none",
      padding: "2px 8px",
      cursor: "pointer",
      fontSize: 11,
      color: C.textLight,
      display: "flex",
      alignItems: "center",
      borderRadius: 3,
      fontFamily: FONT_UI,
    },
    editorContent: {
      flex: 1,
      overflowY: "auto",
      background: C.panelBg,
      fontFamily: FONT_MONO,
      fontSize: 12,
      lineHeight: "18px",
      paddingTop: 2,
      paddingBottom: 2,
    },
    editorLine: {
      display: "flex",
      minHeight: 18,
      cursor: "text",
    },
    lineNumber: {
      width: 40,
      textAlign: "right",
      paddingRight: 10,
      color: C.gutterText,
      background: C.gutterBg,
      fontSize: 11,
      lineHeight: "18px",
      flexShrink: 0,
      userSelect: "none",
    },
    lineContent: {
      paddingLeft: 8,
      whiteSpace: "pre",
      color: C.text,
    },
    consoleContent: {
      flex: 1,
      overflowY: "auto",
      background: C.consoleBg,
      fontFamily: FONT_MONO,
      fontSize: 12,
      lineHeight: "18px",
      padding: "4px 0",
      cursor: "text",
    },
    consoleLine: {
      padding: "0 8px",
      minHeight: 18,
      whiteSpace: "pre-wrap",
      wordBreak: "break-all",
      color: C.consoleOutput,
    },
    consoleInputLine: {
      display: "flex",
      alignItems: "center",
      padding: "0 8px",
      minHeight: 18,
    },
    consoleInput: {
      flex: 1,
      background: "none",
      border: "none",
      outline: "none",
      fontFamily: FONT_MONO,
      fontSize: 12,
      color: C.text,
      padding: 0,
      lineHeight: "18px",
    },
    envContent: {
      flex: 1,
      overflowY: "auto",
      fontSize: 12,
    },
    envToolbar: {
      display: "flex",
      alignItems: "center",
      padding: "4px 8px",
      borderBottom: `1px solid ${C.borderLight}`,
      background: C.toolbarBg,
    },
    envHeader: {
      display: "flex",
      padding: "3px 8px",
      fontSize: 11,
      fontWeight: 600,
      color: C.textMuted,
      borderBottom: `1px solid ${C.borderLight}`,
    },
    envRow: {
      display: "flex",
      padding: "3px 8px",
      borderBottom: `1px solid ${C.borderLight}`,
    },
    plotContent: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      overflow: "auto",
      padding: 8,
      position: "relative",
      background: "#FFFFFF",
    },
    renderingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: "rgba(255,255,255,0.85)",
      zIndex: 10,
    },
    heatmapContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
      maxWidth: 500,
    },
    heatmapWrapper: {
      display: "flex",
      alignItems: "flex-start",
      gap: 8,
    },
    heatmapGrid: {
      display: "grid",
      gridTemplateColumns: "70px repeat(8, 1fr)",
      gridTemplateRows: "auto repeat(8, 1fr)",
      width: "min(100%, 380px)",
      aspectRatio: "auto",
      gap: 1,
      background: "#E0E0E0",
      border: `1px solid ${C.border}`,
    },
    heatmapCorner: {
      background: "#FFFFFF",
    },
    heatmapColLabel: {
      background: "#FFFFFF",
      display: "flex",
      alignItems: "flex-end",
      justifyContent: "center",
      padding: "2px 0",
      minHeight: 50,
    },
    heatmapColText: {
      fontFamily: FONT_MONO,
      fontSize: "min(1.2vw, 9px)",
      color: C.text,
      writingMode: "vertical-rl",
      transform: "rotate(180deg)",
      whiteSpace: "nowrap",
    },
    heatmapRowLabel: {
      background: "#FFFFFF",
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-end",
      paddingRight: 6,
      fontFamily: FONT_MONO,
      fontSize: "min(1.2vw, 9px)",
      color: C.text,
      whiteSpace: "nowrap",
    },
    heatmapCell: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      aspectRatio: "1",
      cursor: "crosshair",
      transition: "outline 0.1s",
      minHeight: 28,
    },
    tooltip: {
      position: "absolute",
      top: "-60px",
      left: "50%",
      transform: "translateX(-50%)",
      background: "rgba(40,40,40,0.92)",
      color: "#FFFFFF",
      padding: "6px 10px",
      borderRadius: 4,
      fontSize: 11,
      whiteSpace: "nowrap",
      zIndex: 100,
      pointerEvents: "none",
      lineHeight: 1.4,
      boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
    },
    legendContainer: {
      display: "flex",
      alignItems: "stretch",
      gap: 4,
      height: 200,
      marginLeft: 4,
    },
    legendBar: {
      width: 16,
      display: "flex",
      flexDirection: "column",
      border: `1px solid ${C.border}`,
      borderRadius: 2,
      overflow: "hidden",
    },
    legendLabels: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      fontSize: 9,
      fontFamily: FONT_MONO,
      color: C.textMuted,
    },
    bossPlot: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    filesContent: {
      flex: 1,
      overflowY: "auto",
      fontSize: 12,
    },
    filesToolbar: {
      display: "flex",
      alignItems: "center",
      padding: "4px 8px",
      borderBottom: `1px solid ${C.borderLight}`,
      background: C.toolbarBg,
    },
    fileRow: {
      display: "flex",
      alignItems: "center",
      padding: "4px 8px",
      borderBottom: `1px solid ${C.borderLight}`,
      fontSize: 12,
      cursor: "pointer",
    },
    packagesContent: {
      flex: 1,
      overflowY: "auto",
    },
    packageRow: {
      display: "flex",
      alignItems: "center",
      padding: "4px 8px",
      borderBottom: `1px solid ${C.borderLight}`,
    },
    statusBar: {
      display: "flex",
      alignItems: "center",
      height: 22,
      background: C.statusBar,
      borderTop: `1px solid ${C.border}`,
      padding: "0 10px",
      fontSize: 11,
      color: C.textMuted,
      gap: 0,
      flexShrink: 0,
    },
    statusSep: {
      margin: "0 6px",
      color: C.borderLight,
    },
    optionsOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: "rgba(0,0,0,0.3)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1000,
    },
    optionsDialog: {
      background: C.bg,
      border: `1px solid ${C.border}`,
      borderRadius: 6,
      width: 560,
      maxHeight: "80vh",
      boxShadow: "0 8px 32px rgba(0,0,0,0.15)",
      display: "flex",
      flexDirection: "column",
    },
    optionsTitle: {
      padding: "12px 16px",
      fontSize: 14,
      fontWeight: 600,
      borderBottom: `1px solid ${C.border}`,
      color: C.text,
    },
    optionsBody: {
      display: "flex",
      flex: 1,
      minHeight: 300,
    },
    optionsSidebar: {
      width: 140,
      borderRight: `1px solid ${C.border}`,
      padding: "8px 0",
      background: C.gutterBg,
    },
    optionsSidebarItem: {
      padding: "6px 12px",
      fontSize: 12,
      color: C.text,
      cursor: "pointer",
    },
    optionsContent: {
      flex: 1,
      padding: 16,
    },
    optionsSelect: {
      width: "100%",
      padding: "6px 8px",
      border: `1px solid ${C.border}`,
      borderRadius: 4,
      fontSize: 12,
      fontFamily: FONT_UI,
      background: C.bg,
      color: C.text,
    },
    optionsFooter: {
      display: "flex",
      justifyContent: "flex-end",
      gap: 8,
      padding: "12px 16px",
      borderTop: `1px solid ${C.border}`,
    },
    optionsBtn: {
      padding: "6px 20px",
      border: `1px solid ${C.border}`,
      borderRadius: 4,
      fontSize: 12,
      cursor: "pointer",
      fontFamily: FONT_UI,
      background: C.toolbarBg,
      color: C.text,
    },
  };
}

export const COMPUTED_STYLES = getStyles();
